const LOAD_PRODUCTS = "LOAD_PRODUCTS";
const ADD_TO_CART = "ADD_TO_CART";
const DELETE_ITEM = "DELETE_ITEM";
const SAVE_FOR_LATER = "SAVE_FOR_LATER";
const ADD_FROM_SAVE = "ADD_FROM_SAVE";
const SET_PRODUCT = "SET_PRODUCT";
const CHECKOUT = "CHECKOUT"

export { LOAD_PRODUCTS, ADD_TO_CART, DELETE_ITEM, SAVE_FOR_LATER, ADD_FROM_SAVE, SET_PRODUCT, CHECKOUT }